name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
        
      - name: Cppcheck code Substring
        run: cppcheck Time-to-code/c_program/Substring
      
      - name: Cppcheck code Prime
        run: cppcheck Time-to-code/c_program/Prime
